# Screenshots
for_window [app_id="flameshot"] floating enable; border pixel 2

for_window [app_id="proton-bridge"] floating enable; border pixel 2

# Volume control window
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable; border pixel 2

# Screen layout editor
for_window [app_id="nwg-displays"] floating enable; border pixel 2

for_window [title=".*Discord$"] move container to workspace 2
