mode "office-control" {
    bindsym $mod+KP_0 exec "/home/mich/bin/./office-control light_off; swaymsg mode default"
    bindsym $mod+KP_1 exec "/home/mich/bin/office-control light_on; swaymsg mode default"
    bindsym $mod+KP_2 exec "/home/mich/bin/./office-control light_bright; swaymsg mode default"
    bindsym $mod+KP_3 exec "/home/mich/bin/./office-control toggle_preset; swaymsg mode default"
    bindsym $mod+KP_7 exec "/home/mich/bin/./office-control climate_cool; swaymsg mode default"
    bindsym $mod+KP_8 exec "/home/mich/bin/./office-control climate_off; swaymsg mode default"
    bindsym $mod+KP_9 exec "/home/mich/bin/./office-control climate_heat; swaymsg mode default"
    bindsym Escape mode "default"
}

bindsym $mod+KP_0 mode "office-control"