# Terminal
bindsym $mod+Return exec "kitty tmux"
bindsym $mod+Shift+Return exec "kitty"

# App launcher
bindsym $mod+d exec rofi -show drun

# File manager
bindsym $mod+Home exec thunar

# Screenshot
bindsym Print exec "flameshot gui"

# RPN calculator
bindsym XF86Calculator exec "kitty --title=Calculator\ repocalc  repocalc"
bindsym $mod+KP_Add exec "kitty --title=Calculator\ repocalc repocalc"
# These can go in shared config since both Sway and i3 support matching on title
for_window [title="Calculator repocalc"] floating enable
for_window [title="Calculator repocalc"] border pixel 4
for_window [title="Calculator repocalc"] move scratchpad
for_window [title="Calculator repocalc"] scratchpad show