# Required software:
# - libpulse
# - pipewire-pulse
# - playerctl

# Media button controls
# Volume control
bindsym XF86AudioMute exec "amixer set Master toggle"
bindsym XF86AudioRaiseVolume exec "amixer -q sset Master 5%+"
bindsym Shift+XF86AudioRaiseVolume exec "amixer -q sset Master 1%+"
bindsym XF86AudioLowerVolume exec "amixer -q sset Master 5%-"
bindsym Shift+XF86AudioLowerVolume exec "amixer -q sset Master 1%-"

bindsym XF86AudioPlay exec "playerctl play-pause"
bindsym XF86AudioPause exec "playerctl play-pause"
bindsym XF86AudioNext exec "playerctl next"
bindsym XF86AudioPrev exec "playerctl previous"

# Switch between outputs

# Speakers
bindsym $mod+XF86AudioPlay exec "pactl set-default-sink $(pactl list sinks short | grep 'Scarlett' | awk '{ print $1 }')"
# Steelseries wireless headphones
bindsym $mod+XF86AudioMute exec "pactl set-default-sink $(pactl list sinks short | grep 'SteelSeries' | awk '{ print $1 }')"
# Bluetooth headphones
bindsym $mod+Shift+XF86AudioMute exec "pactl set-default-sink $(pactl list sinks short | grep 'a2dp-sink' | awk '{ print $1 }')"