# session-control.conf
# Common i3/sway configuration about session control:
# locking, log out / restart / shutdown

bindsym $mod+l exec "/home/mich/bin/mich-lock.sh"
bindsym $mod+z exec "/home/mich/bin/mich-lock.sh"
bindsym $mod+Shift+z exec "/home/mich/bin/mich-lock.sh suspend"