
# Empty container to use only half of the parent container.
# No known equivalent in sway, and the i3 one is hacky to begin with
bindsym $mod+Shift+numbersign exec "i3 open"

# Work setup needs redoing.
bindsym $mod+Ctrl+w exec "/home/mich/.i3/setups/./work.bash"
#-------------------------------------------------------------------------------

