# Screenshots
for_window [class="flameshot"] floating enable; border pixel 2

for_window [class="Proton Mail Bridge"] floating enable; border pixel 2

# Volume control window
for_window [class="Pavucontrol"] floating enable; border pixel 2

# Screen layout editor
for_window [class="Arandr"] floating enable; border pixel 2

for_window [title=".*Discord$"] move container to workspace 2

