bar {
    # This config for position has to be in same block, otherwise there
    # will be 2 bars
    position top
    status_command ~/.config/i3/bar.sh
    tray_output primary
    workspace_min_width 36

    colors {
        background #$c_b_bg
        statusline #$c_b_status_text
        separator  #$c_b_separator

        focused_workspace \
          #$c_b_focused_ws_border \
          #$c_b_focused_ws_bg \
          #$c_b_focused_ws_text
        active_workspace  \
          #$c_b_active_ws_border \
          #$c_b_active_ws_bg \
          #$c_b_active_ws_text
        inactive_workspace\
          #$c_b_inactive_ws_border \
          #$c_b_inactive_ws_bg \
          #$c_b_inactive_ws_text
        urgent_workspace  \
          #$c_b_urgent_ws_border \
          #$c_b_urgent_ws_bg \
          #$c_b_urgent_ws_text
        binding_mode      \
          #$c_b_binding_mode_border \
          #$c_b_binding_mode_bg \
          #$c_b_binding_mode_text
    }
}