mode "office-control" {
    bindsym $mod+Mod2+KP_0 exec "/home/mich/bin/./office-control light_off; i3-msg mode default"
    bindsym $mod+Mod2+KP_1 exec "/home/mich/bin/office-control light_on; i3-msg mode default"
    bindsym $mod+Mod2+KP_2 exec "/home/mich/bin/./office-control light_bright; i3-msg mode default"
    bindsym $mod+Mod2+KP_3 exec "/home/mich/bin/./office-control toggle_preset; i3-msg mode default"
    bindsym $mod+Mod2+KP_7 exec "/home/mich/bin/./office-control climate_cool; i3-msg mode default"
    bindsym $mod+Mod2+KP_8 exec "/home/mich/bin/./office-control climate_off; i3-msg mode default"
    bindsym $mod+Mod2+KP_9 exec "/home/mich/bin/./office-control climate_heat; i3-msg mode default"
    bindsym Escape mode "default"
}

bindsym $mod+Mod2+KP_0 mode "office-control"