workspace 1 output DisplayPort-1
workspace 3 output DisplayPort-1
workspace 5 output DisplayPort-1
workspace 7 output DisplayPort-1

workspace 2 output DisplayPort-2
workspace 4 output DisplayPort-2
workspace 6 output DisplayPort-2
workspace 8 output DisplayPort-2

workspace 11 output HDMI-A-0
workspace 13 output HDMI-A-0
workspace 15 output HDMI-A-0
workspace 17 output HDMI-A-0

workspace 12 output DisplayPort-0
workspace 14 output DisplayPort-0
workspace 16 output DisplayPort-0
workspace 18 output DisplayPort-0